
import { NextAuthProvider } from "./providers";
import { useEffect } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import Script from "next/script";

import Providers from "@/util/provider";

export const metadata = {
  title: "Mercadinho",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="pt">
      <body>
        <NextAuthProvider>
          <NextTopLoader
            color="#ff0"
            initialPosition={0.08}
            crawlSpeed={150}
            height={4}
            crawl={true}
            showSpinner={true}
            easing="ease"
            speed={10}
          />
          <Providers> {children} </Providers>
        </NextAuthProvider>
      </body>
      <Script
        src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.16.17/js/uikit.min.js"
        strategy="afterInteractive"
      />
    </html>
  );
}
